### ISSUE TITLE
[MKT-73-39] Simplify complex information: #DeFiMadeSimple: Curve Edition

### ISSUE THREAD

**Issue by JKtranslator** [yearn/yearn-marketing#39]
Rationale: Yearn's main product is the yVault. When trying to get a sense of how the APY is calculated, it became clear how much the yVaults simplify the process of investing. The idea is to create a series explaining the work needed to do manually what the yVault (or one of the strategies) does for its users.

Proposition: To create an infographic showing all steps needed to get the highest yield at Curve and then to explain the process using the yVault.

Content:\
1\. LP at a Curve pool\
2\. Decision: Stake the LP at Curve (gauge)/Go to Convex\
3\. Claim CRV\
4\. Stake CRV (veCRV) to Boost your rewards\
5\. Claim Bonus Reward (if any)\
6\. Sell CRV/Rewards\
7\. Back at step 1

Resources: [https://resources.curve.fi/](https://resources.curve.fi/)\
[https://github.com/yearn/yearn-marketing/issues/36](https://github.com/yearn/yearn-marketing/issues/36)

Objectives:

* Explain what yield farming is (In Curve context)
* To highlight the benefits of using yVaults (Less manual work; gas savings; Optimization between strategies to get best yield; don't have to deal with other protocols like convex)

**Comment by DarkGhost7** [comment]
- Curve is a protocol that mainly enables token swaps between like-kind tokens (wbtc <> renbtc, seth <> reth, ect) with low slippage.
- A few points curve doesn't offer low-slippage because of attracting users to provide liquidity this makes it sound the same as say uniswap. It has math that lets you do like-kind swaps for lower slippage than a normal x*y curve. 
- `The incentives to these users are the fees and extra rewards given by the protocol itself or by other protocols. Below are shown the steps to provide the liquidity and collect the rewards.` great
- This process is called `Yield Farming`
- When using Curve, the user needs to deposit the lp token into Curve's "Gauge" for that token. 
- Depending __on__ the liquidity pool, extra rewards can be given out by the tokens' themselves to this pool as rewards. These incentivize people to deposit into the liquidity pool. 
- (yVaults section): something simple, secure`,` and available for everyone.
- Vaults use automated strategies to grab the best opportunities for each protocol which meets yearn's security standards. 
- Every transaction for each strategies batches users funds to save gas, resulting in lower gas fees for all vault depositors than if they farmed solo. 
- If you don't have the token needed, you can Zap it when making the deposit`.` (only one period here)
- `Simply` deposit your token and return when you want to check the yield gained. No need to make decisions and monitor your position 24/7. 

@JKtranslator my fixes

**Comment by JKtranslator** [comment]
Fixes applied
![Curve Edition](https://user-images.githubusercontent.com/88235023/161848672-b622a520-aecf-40c2-9842-3ef50fa0e7ae.png)

As blocks
![1-Slide-1](https://user-images.githubusercontent.com/88235023/161848725-c68dd9d7-6a81-4150-aa2b-a4862c30dda0.jpg)
![2-infoblock](https://user-images.githubusercontent.com/88235023/161848731-809def3d-44fe-4b57-9c77-bdc9a77c4572.jpg)

**Comment by JKtranslator** [comment]
Fixed.
